# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoordinatorExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoordinatorExample
  pod 'CoreCoordinator', :path => '../'

  pod 'CoreLauncher',
    :git => 'https://github.com/skibinalexander/CoreLauncher.git/',
    :tag => '0.0.2'

  pod 'PanModal'

end
